### ISSUE TITLE
Update the tracer config format to a list of watched resources instead of keyed by GVK.

### ISSUE THREAD

**Issue by drmorr0** [acrlabs/simkube#62]
## Description
The current tracer config format looks like this:

```
trackedObjects:
  <gvk for object>:
    podSpecTemplatePath: /json/patch/path/to/pod/template/spec
    trackLifecycle: true/false (optional)
```

I think a better config format would be

```
trackedObjects:
  - gvk: <gvk for object>:
    podSpecTemplatePath: /json/patch/path/to/pod/template/spec
    trackLifecycle: true/false (optional)
```

[code hint](https://github.com/acrlabs/simkube/blob/master/lib/rust/config.rs)
